# @package _global_

# paths:
#   data_root: /data
#   code_root: /root
#   traces: test_traces
#
#   model: ${.data_root}/models/Qwen2.5-Math-1.5B
#
#   train_files: ${.data_root}/gsm8k/train.parquet
#   val_files: ${.data_root}/gsm8k/test.parquet
#
#   reward_file: ${.code_root}/duet/training/reward.py
#   rollout_dir: ${.data_root}/${.traces}/test_rollout_data
#   profiler: ${.data_root}/${.traces}
#

paths:
  data_root: /data
  code_root: /root

  model: ${.data_root}/models/Qwen2.5-Math-1.5B
  train_files: ${.data_root}/gsm8k/train.parquet
  val_files: ${.data_root}/gsm8k/test.parquet
  reward_file: ${.code_root}/duet/training/reward.py

  run_id: ${oc.env:DUET_RUN_ID}
  run_dir: ${oc.env:DUET_RUN_DIR}

  rollout_dir: ${.run_dir}/rollout_data
  profiler: ${.run_dir}/profiler


custom_config:
  seed: 90


algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false

data:
  train_files: ${paths.train_files}
  val_files: ${paths.val_files}
  train_batch_size: 512
  max_prompt_length: 1024
  max_response_length: 3072
  filter_overlong_prompts: true
  truncation: error

  # Profiling overrides
  shuffle: true #true # false
  train_max_samples: 2048 #1024

reward:
  custom_reward_function:
    path: ${paths.reward_file}
    name: custom_reward_function

actor_rollout_ref:
  model:
    path: ${paths.model} 
    use_remove_padding: true
    enable_gradient_checkpointing: true

  actor:
    ppo_mini_batch_size: 128
    ppo_micro_batch_size_per_gpu: 2
    ppo_max_token_len_per_gpu: 8192
    use_dynamic_bsz: true

    use_kl_loss: false
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    entropy_coeff: 0

    optim:
      lr: 1e-6

    fsdp_config:
      param_offload: false
      optimizer_offload: false

      #================================================
      # For determinism, setting seed to a specific 
      # number and full_determinism to true
      #================================================
      seed: ${custom_config.seed}
      full_determinism: false


    profiler:
      enable: false # set to true later
      all_ranks: false
      ranks: [0]
      save_path: ${paths.profiler}/actor  
      tool_config:
        torch:
          discrete: true
          contents: [cpu, cuda]

  rollout:
    name: vllm
    tensor_model_parallel_size: 1
    response_length: ${data.max_response_length} 
    disable_log_stats: false

    gpu_memory_utilization: 0.4
    enable_chunked_prefill: false
    enforce_eager: false
    free_cache_engine: true

    n: 8
    max_num_seqs: 640

    log_prob_micro_batch_size_per_gpu: 2
    log_prob_use_dynamic_bsz: true
    log_prob_max_token_len_per_gpu: 8192

    #================================================
    # For determinism, setting seed to a specific 
    # number and full_determinism to true
    #================================================
    seed: ${custom_config.seed}
    full_determinism: false



    checkpoint_engine:
      update_weights_bucket_megabytes: 256

    profiler:
      enable: false # set to true later
      save_path: ${paths.profiler}/rollout
      all_ranks: false
      ranks: [0]
      tool_config:
        torch:
          discrete: true

    agent:
      num_workers: 2
      agent_loop_manager_class: duet.scheduler.manager.MyAgentLoopManager

  ref:
    log_prob_micro_batch_size_per_gpu: 2
    log_prob_use_dynamic_bsz: true
    log_prob_max_token_len_per_gpu: 8192

    fsdp_config:

      param_offload: false

      #================================================
      # For determinism, setting seed to a specific 
      # number and full_determinism to true
      #================================================
      seed: ${custom_config.seed}
      full_determinism: false


trainer:
  critic_warmup: 0

  logger:
    - console
    - mlflow

  project_name: verl_grpo_gsm8k_profile
  experiment_name: ${paths.run_id}


  n_gpus_per_node: 1
  nnodes: 1

  save_freq: 20
  test_freq: 8

  # Profiling run
  total_epochs: 2
  total_training_steps: null


  rollout_data_dir: ${paths.rollout_dir}
  default_local_dir: ${paths.run_dir}/checkpoints

  val_before_train: false

  duet:
    # Options:: difficulty_only | length_only | noops | joint
    # Options:: short | refill

    scheduler: noops
    underfill_policy: refill
    scheduler_options:
      - noops
      # - difficulty_only
      # - length_only

global_profiler:
  tool: torch
  steps: [1]
  save_path: ${paths.profiler}

ray_kwargs:
  ray_init:
    runtime_env:
      worker_process_setup_hook: duet.training.profile_patch.patch_verl_for_profiling
